-- MySQL Script generated by MySQL Workbench
-- Fri Sep  1 05:22:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Livraria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Livraria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Livraria` ;
USE `Livraria` ;

-- -----------------------------------------------------
-- Table `Livraria`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Livraria`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `NomeAutor` VARCHAR(45) NOT NULL,
  `Nascimento` DATE NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livraria`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Livraria`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `NomeCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livraria`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Livraria`.`Livro` (
  `idLivro` INT NOT NULL AUTO_INCREMENT,
  `Publicação` DATE NOT NULL,
  `Preço` DECIMAL NOT NULL,
  PRIMARY KEY (`idLivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livraria`.`Autor_has_Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Livraria`.`Autor_has_Livro` (
  `Autor_idAutor` INT NOT NULL,
  `Livro_idLivro` INT NOT NULL,
  INDEX `fk_Autor_has_Livro_Livro1_idx` (`Livro_idLivro` ASC) VISIBLE,
  INDEX `fk_Autor_has_Livro_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_has_Livro_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `Livraria`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Livro_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `Livraria`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livraria`.`Categoria_has_Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Livraria`.`Categoria_has_Livro` (
  `Categoria_idCategoria` INT NOT NULL,
  `Livro_idLivro` INT NOT NULL,
  INDEX `fk_Categoria_has_Livro_Livro1_idx` (`Livro_idLivro` ASC) VISIBLE,
  INDEX `fk_Categoria_has_Livro_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_has_Livro_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `Livraria`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_Livro_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `Livraria`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
